<?php
$pageTitle = 'My Pay Slip';
require_once __DIR__ . '/../../includes/init.php';
requireModuleAccess('payslip_own');

$pdo = getDBConnection();
$facultyId = requireTeachingProfile($pdo);
$linkedFaculty = getLinkedFaculty($pdo);
$payslips = getTeacherPayslips($pdo, $facultyId);

$payslip = null;
if (isset($_GET['view']) && is_numeric($_GET['view'])) {
    $stmt = $pdo->prepare("
        SELECT ps.*, f.staff_id, f.first_name, f.last_name, f.department, f.faculty_type
        FROM payslips ps
        JOIN faculty f ON ps.faculty_id = f.id
        WHERE ps.id = ? AND ps.faculty_id = ?
    ");
    $stmt->execute([(int) $_GET['view'], $facultyId]);
    $payslip = $stmt->fetch();
    if (!$payslip) {
        setFlash('error', 'Pay slip not found.');
        redirect(BASE_URL . '/modules/faculty/my_payslip.php');
    }
}

require_once __DIR__ . '/../../includes/header.php';
?>

<?php if ($payslip): ?>
<div class="card">
    <div class="card-header">
        <h3>Pay Slip — <?= sanitize($payslip['pay_period']) ?></h3>
        <button onclick="printSection('payslipPrint')" class="btn btn-primary btn-sm">Print</button>
    </div>
    <div class="card-body" id="payslipPrint">
        <div class="receipt-box">
            <div class="receipt-header">
                <img src="<?= LOGO_PATH ?>" alt="<?= APP_INSTITUTION ?>" class="brand-logo brand-logo--receipt">
                <p>Employee Pay Slip</p>
            </div>
            <div class="detail-grid">
                <div class="detail-item"><label>Staff ID</label><span><?= sanitize($payslip['staff_id']) ?></span></div>
                <div class="detail-item"><label>Employee Name</label><span><?= sanitize($payslip['first_name'] . ' ' . $payslip['last_name']) ?></span></div>
                <div class="detail-item"><label>Department</label><span><?= sanitize($payslip['department'] ?? '-') ?></span></div>
                <div class="detail-item"><label>Pay Period</label><span><?= sanitize($payslip['pay_period']) ?></span></div>
                <div class="detail-item"><label>Pay Date</label><span><?= formatDate($payslip['pay_date']) ?></span></div>
                <div class="detail-item"><label>Basic Salary</label><span><?= formatCurrency((float) $payslip['basic_salary']) ?></span></div>
                <div class="detail-item"><label>Allowances</label><span><?= formatCurrency((float) $payslip['allowances']) ?></span></div>
                <div class="detail-item"><label>Deductions</label><span><?= formatCurrency((float) $payslip['deductions']) ?></span></div>
                <div class="detail-item"><label>Net Salary</label><span style="font-size:1.2rem;font-weight:700;color:var(--success);"><?= formatCurrency((float) $payslip['net_salary']) ?></span></div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>

<div class="card">
    <div class="card-header"><h3>My Pay Slips</h3></div>
    <div class="card-body">
        <div class="detail-grid" style="margin-bottom:16px;">
            <div class="detail-item"><label>Employee</label><span><?= sanitize($linkedFaculty['first_name'] . ' ' . $linkedFaculty['last_name']) ?></span></div>
            <div class="detail-item"><label>Staff ID</label><span><?= sanitize($linkedFaculty['staff_id']) ?></span></div>
        </div>
        <?php if (empty($payslips)): ?>
        <div class="empty-state">
            <h4>No pay slips yet</h4>
            <p>Your payslips will appear here once generated by the finance office.</p>
        </div>
        <?php else: ?>
        <div class="table-responsive">
            <table class="data-table">
                <thead><tr><th>Period</th><th>Net Salary</th><th>Pay Date</th><th>Action</th></tr></thead>
                <tbody>
                    <?php foreach ($payslips as $ps): ?>
                    <tr>
                        <td><?= sanitize($ps['pay_period']) ?></td>
                        <td><?= formatCurrency((float) $ps['net_salary']) ?></td>
                        <td><?= formatDate($ps['pay_date']) ?></td>
                        <td><a href="?view=<?= (int) $ps['id'] ?>" class="btn btn-secondary btn-sm">View / Print</a></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php endif; ?>
    </div>
</div>

<?php require_once __DIR__ . '/../../includes/footer.php'; ?>
